### ISSUE TITLE
HOME should not be the /workspace

### ISSUE THREAD

**Issue by jkutner** [heroku/pack-images#45]
In order to resolve #42 and make some of the shimmed buildpacks work, we've set `$HOME` to `/workspace` in `heroku/pack:18` for the `heroku` user. But in the future we want to avoid this so it matches `heroku/pack:18-build`.

We can/should not set `$HOME` to `/workspace` in `heroku/pack:18-build` because it can cause secrets, local caches in dot dirs, etc to end up in the launch image.

**Comment by jkutner** [comment]
Fixing this will probably require changes in the shimmed buildpacks

**Comment by edmorley** [comment]
@jkutner Is this ok to close out? It seems `HOME` is now `/app`:
https://github.com/heroku/pack-images/blob/d724bd94e8dc9d6cb2d76b49b5469cdee0347f29/Dockerfile.run#L15

**Comment by edmorley** [comment]
It looks like this was resolved by #43 / #54, feel free to reopen if there is work left to do :-)
