### ISSUE TITLE
Failed to download standard library for bootstrapping!

### ISSUE THREAD

**Issue by qw3r** [heroku/pack-images#71]
Hi!

We've run into the issue mentioned in the subject starting today.

We tried to run the following command on our php app:

    pack build our-php-app --builder heroku/buildpacks:18 --buildpack heroku/php,heroku/procfile

and the output is:

    ===> BUILDING
    [builder]
    [builder]  !     ERROR: Failed to download standard library for bootstrapping!
    [builder]  !
    [builder]  !     This is most likely a temporary internal error. If the problem
    [builder]  !     persists, make sure that you are not running a custom or forked
    [builder]  !     version of the Heroku PHP buildpack which may need updating.
    [builder]
    [builder] ERROR: failed to build: exit status 1`

I've managed to trace back to this line in the php buildpack: `https://github.com/heroku/heroku-buildpack-php/blob/9760ff33fa8dec0baae3bd8040dd4e49c4ffa271/bin/compile#L33`) 
The buildpack is installed into `pack-images/buildpacks/php` dir during the build. 

I've removed the "--silent" option of the curl command suspected to cause the problem, and turned out the process is not permitted to write its output file.

    ===> BUILDING
    [builder]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    [builder]                                  Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
    [builder] Warning: /cnb/buildpacks/heroku_php/0.0.5.2/target/bin/util/stdlib.sh:
    [builder] Warning: Permission denied
    100  5060  100  5060    0     0  10541      0 --:--:-- --:--:-- --:--:-- 10519
    [builder] curl: (23) Failed writing body (0 != 5060)
    [builder]
    [builder]  !     ERROR: Failed to download standard library for bootstrapping!
    [builder]  !
    [builder]  !     This is most likely a temporary internal error. If the problem
    [builder]  !     persists, make sure that you are not running a custom or forked
    [builder]  !     version of the Heroku PHP buildpack which may need updating.
    [builder]
    [builder] ERROR: failed to build: exit status 1

a little more investigation showed that the process is running as `heroku` but the `/cnb/buildpacks` is owned the the root user.

Do you think there is a problem with `pack` itself, or it there a bug in the builder of heroku/buildpacks:18 ?

**Comment by jkutner** [comment]
I think #65 will fix this

**Comment by jweaver-personal** [comment]
The stdlib issue also exists with the python buildpack.

[[36mbuilder[0m] -----> Installing python-3.7.6
[[36mbuilder[0m] -----> Installing pip
[[36mbuilder[0m] -----> Installing dependencies with Pipenv 2018.5.18…
[[36mbuilder[0m]        Installing dependencies from Pipfile.lock (ddf601)…
[[36mbuilder[0m] -----> Installing SQLite3
[[36mbuilder[0m] Sqlite3 successfully installed.
[[36mbuilder[0m] /tmp/stdlib.sh: line 72: /cnb/buildpacks/heroku_python/0.0.5.2/target/bin/../export: Permission denied

**Comment by jkutner** [comment]
@jweaver-personal we're working on this now, and should have a fix by the end of today

**Comment by jkutner** [comment]
The new `heroku/buildpacks:18` has been released, and this should work now. I'm going to close this PR, but please let us know if you continue to have problems and we'll reopen.
